blog_App/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from . import views
from rest_framework import routers
from blog_App.views import UserViewSet, NewViewSet, CategoryViewSet

router = routers.DefaultRouter()
router.register('users', UserViewSet)
router.register('news', NewViewSet)
router.register('category-detail', CategoryViewSet)

urlpatterns = [
    path('', views.home, name='index'),
    path('home', views.home, name='home'),
    # Noticias
    path('news', views.newsView, name='newsView'),
    path('news/category/<int:category_id>/', views.newsView_filter, name="category"),
    path('news/newsitem/<int:news_id>/', views.newsView_item, name="newsitem"),
    path('create/new', login_required(views.createNew), name='create_new'),
    path('update/new/<int:news_id>', login_required(views.updateNew), name='update_new'),
    path('delete/new/<int:news_id>', login_required(views.deleteNew), name='delete_new'),
    path('news/table', login_required(views.newsTable), name='news_table'),
    path('news/table/<int:category_id>', login_required(views.newsTable_Filter), name='news_tableCategory'),
    # Usuarios
    path('login', LoginView.as_view(),name='login'),
    path('logout', LogoutView.as_view(),name='logout'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('change_password', views.MyPasswordChangeView.as_view(), name='password_change'),
    path('change_password/done', views.MyPasswordChangeDoneView.as_view(), name='password_change_done'),

    # Api
    path('api/', include(router.urls))

]

pnud_py_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls), 
    path('', include('blog_App.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_App/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class category(models.Model):
    """
    In this model are the categories to create the new news.
    """
    name=models.CharField(max_length=60)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name='category'
        verbose_name_plural='categories'

    def __str__(self):
        return self.name

class news(models.Model):
    """
    The news created in the application are saved in this model.
    Title, text and category are required.
    """
    title=models.CharField(max_length=60)
    text = models.TextField()
    image=models.ImageField(upload_to='blog',null=True,blank=True)
    author=models.ForeignKey(User, on_delete=models.CASCADE)
    categories=models.ManyToManyField(category)
    published_date = models.DateTimeField(
            blank=True, null=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name='new'
        verbose_name_plural='news'
    
    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog_App/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import news, category
class RegisterForm(UserCreationForm):

    first_name = forms.CharField(
        label='Nombre',
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Nombre'
            }
        )
    )

    last_name = forms.CharField(
        label='Apellido',
        min_length=2,
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Apellido'
            }
        )
    )
    
    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'Email'
            }
        )
    )
    
    username = forms.CharField(
        min_length=4,
        max_length=30,
        label='Username',
        widget=forms.TextInput(
            attrs={
                'placeholder': "Username"
            }
        )
    )

    password1 = forms.CharField(
        label='Contraseña',
        max_length=70,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña'
            }
        )
    )

    password2 = forms.CharField(
        label='Confirmar Contraseña',
        max_length=70,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Confirmar contraseña'
            }
        )
    )
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username',
                'email', 'password1', 'password2')

class NewForm(forms.ModelForm):

    class Meta:
        model = news
        fields = ('title', 'text', 'image', 'categories')

    title = forms.CharField(label='Título:',
                            widget=forms.TextInput(
                                attrs={
                                    'class': 'form-control',
                                    'placeholder': 'Ingrese un título',
                                }))
    text = forms.CharField(label='Contenido:', widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Contenido',
        'rows': 4
    }))
    image = forms.ImageField(required=False, label='Imagen:', widget=forms.ClearableFileInput(attrs={
        'class': 'form-control',
    }))
    categories = forms.ModelMultipleChoiceField(queryset=category.objects.all(), label='Categorias:', widget=forms.SelectMultiple(attrs={
        'class': 'form-control',
    }))

blog_App/views.py
from django.utils import timezone
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
from django.contrib.auth import login, authenticate, logout
from django.views.generic import CreateView
from .forms import NewForm, RegisterForm
from django.contrib.auth.models import User
from .models import news, category
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView, PasswordResetDoneView
from rest_framework import viewsets, serializers, permissions

# Create your views here.
def home(request): 
    """
    Main View with the most relevant news
    """
    noticias = news.objects.all()[:6]
    return render(request,'home.html',{"news":noticias})


def createNew(request):
    """
    View to create the new news.
    Title, Text and Categories are required
    """
    if request.method == "POST":
        form = NewForm(request.POST, request.FILES)
        if form.is_valid():
            new = form.save(commit=False)
            print(request.POST, request.FILES)
            if  request.POST.get('image', False) == '':
                new.image = 'blog/noticia_defecto.jpg'
            new.author = request.user
            new.published_date = timezone.now()
            new.save()
            form.save_m2m()
            return redirect('news_table')
        else:
            return render(request, 'create_new.html', {'form': form})
    else:
        form = NewForm()
        return render(request, 'create_new.html', {'form': form})

def updateNew(request, news_id):
    """
    View to edit the old news. You can change the title, description, image and category
    """
    new = get_object_or_404(news, id=news_id)
    if request.method == "POST":
        form = NewForm(request.POST, request.FILES, instance=new)
        if form.is_valid():
            if  request.POST.get('image', False) == '':
                new.image = 'blog/noticia_defecto.jpg'
            new.author = request.user
            new.save()
            form = NewForm()
            return redirect('news_table')
        else:
            return render(request, 'edit_new.html', {'form': form})
    else:
        form = NewForm(instance=new)
        return render(request, 'edit_new.html', {'form': form})

def newsView(request): 
    """
    View to show all news the created.
    """
    dt_category=category.objects.all()
    dt_noticias = news.objects.all()
    return render(request,'newsindex.html',{"news":dt_noticias, "categories":dt_category})

def newsView_filter(request, category_id):
    """
    View to show all the news related to a specific category.
    """
    dt_category=category.objects.get(id=category_id)
    dt_noticias = news.objects.filter(categories=dt_category)
    return render(request,'newscategory.html',{"news":dt_noticias, "categories":dt_category})

def newsView_item(request, news_id): 
    """
    View to show the details of a specific news.
    """
    titleNews=""
    dt_noticias = news.objects.filter(id=news_id)
    titleNews=dt_noticias[0]
    return render(request,'newsitem.html',{"news":dt_noticias,"titleNews":titleNews})

def deleteNew(request, news_id):
    """
    View to delete a specific new.
    """
    new = get_object_or_404(news, id=news_id)
    new.delete()
    return redirect('news_table')

def newsTable(request):
    """
    View to show a table with the news created by a user with the active session.
    """
    dt_category=category.objects.all()
    dt_noticias = news.objects.filter(author_id=request.user.id)
    return render(request,'news_table.html',{"news":dt_noticias, "categories":dt_category})

def newsTable_Filter(request, category_id):
    """
    View to show a table with all the news related to a specific category and a user with the active session.
    """
    dt_categories=category.objects.all()
    dt_category=category.objects.get(id=category_id)
    dt_noticias = news.objects.filter(author_id=request.user.id).filter(categories=dt_category)
    return render(request,'news_table.html',{"news":dt_noticias, "categories":dt_categories})

class RegisterView(CreateView):
    """
    View to register a new user.
    """
    model = User
    form_class = RegisterForm
    template_name = "register.html"

    def form_valid(self, form):
        form.save()
        usuario = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        usuario = authenticate(username=usuario, password=password)
        login(self.request, usuario)
        return redirect('home')

class MyPasswordChangeView(PasswordChangeView):
    """
    View to change the password of a user with the active session.
    """
    template_name='registration/password_change.html'
    success_url=reverse_lazy('password_change_done')

class MyPasswordChangeDoneView(PasswordResetDoneView):
    """
    View to confirm the password change.
    """
    template_name='registration/password_change_done.html'

# API Views
class UserSerializer(serializers.HyperlinkedModelSerializer):
    """
    Api View to query user information.
    (username, email, first_name and last_name)
    """
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

class UserViewSet(viewsets.ModelViewSet):
    """
    Api View to query users information.
    (username, email, first_name and last_name)
    """
    queryset = User.objects.all()
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]

class NewSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = news
        fields = ['title', 'text', 'image', 'categories', 'author']

class NewViewSet(viewsets.ModelViewSet):
    """
    Api View to query news information.
    ('title', 'text', 'image', 'categories', 'author')
    """
    queryset = news.objects.all()
    serializer_class = NewSerializer
    permission_classes = [permissions.IsAuthenticated]

class CategorySerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = category
        fields = ['name']

class CategoryViewSet(viewsets.ModelViewSet):
    """
    Api View to query categories information.
    (name)
    """
    queryset = category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = [permissions.IsAuthenticated]

blog_App/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/home.css' %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <link href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css" rel="stylesheet" />
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/1.0.0/js/dataTables.responsive.js"></script>
    <script src="https://cdn.datatables.net/rowreorder/1.2.7/js/dataTables.rowReorder.min.js"></script>
    <title>{% block title %} {% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark" data-bs-theme="dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="container-fluid">
                    <div class="row justify-content-between">
                        <div class="col-3">
                            <div class="navbar-nav">
                                <a class="nav-link active" aria-current="page" href="/home">Inicio</a> {% if user.is_authenticated %}
                                <a class="nav-link" href="/news/table">Noticias</a>
                                <a class="nav-link" href="/create/new">Crear Noticia</a> {% else %}
                                <a class="nav-link" href="/news">Noticias</a> {% endif %}

                            </div>
                        </div>
                        <div class="col-2">
                            <div class=" navbar-nav ">
                                {% if user.is_authenticated %}
                                <div class="dropdown">
                                    <button class="btn btn-outline-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Configuración
                                    </button>
                                    <ul class="dropdown-menu">
                                        <a class="dropdown-item" href="{% url 'password_change'%}">Cambiar
                                            Contraseña</a>
                                        <a class="dropdown-item" href="{% url 'logout'%}?next={{request.path}}">Cerrar
                                            Sesión</a>
                                    </ul>
                                </div>
                                {% else %}
                                <a class="nav-link " href="/login">Iniciar Sesion</a>
                                <a class="nav-link " href="#">/</a>/
                                <a class="nav-link " href="/register">Registrar</a> {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <div class="jumbotron ">
        <h1 class="text-center ">{% block titleView %} {% endblock %}</h1>
    </div>
    <div class="container">
        <br> {% block content %} {% endblock %}
    </div>
    <hr>
    <footer class="footer ">
        <div class="container ">
            <div class="row ">
                <div class="col-sm d-flex flex-column ">
                    <div class="container ">
                        <p>
                            <h4 class="text-center ">Contactanos</h4>
                            <ul>
                                <li class="list-group-item ">Quito 0000, Iñaquito, Ecuador</li>
                                <li class="list-group-item ">+594999999999</li>
                                <li class="list-group-item ">example@hotel.com</li>
                            </ul>
                        </p>
                    </div>
                </div>
                <div class="col-sm d-flex flex-column ">
                    <div class="container ">
                        <p>
                            <h4 class="text-center ">Sobre Nosotros</h4>
                            <p class="text-center ">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc efficitur nibh eu finibus efficitur. Nullam dui dolor, porta eget libero ac, ultrices pretium nisi.
                            </p>
                        </p>
                    </div>
                </div>
                <div class="col-sm d-flex flex-column ">
                    <div class="container ">
                        <p>
                            <h4 class="text-center ">Acuerdos</h4>
                            <ul>
                                <li class="list-group-item "><a href="# " class="link ">Política de privacidad</a></li>
                                <li class="list-group-item "><a href="# " class="link ">Aviso legal</a></li>
                                <li class="list-group-item "><a href="# " class="link ">Cookies</a></li>
                            </ul>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js " integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN " crossorigin="anonymous "></script>
</body>

</html>

blog_App/templates/create_new.html
{% extends "base.html" %}
{% block title %}Crear Noticia{% endblock %}
{% load widget_tweaks %}
{% block content %}
<div class="row">
    <div class="col-2"></div>
    <div class="col-8">
        <div class="card" style="width: 100%; background: #cbd5db;">
            <div class="card-header">
                <h3 class="card-title">Nueva Noticia</h3>
            </div>
            <div class="card-body">
                <form method="POST" class="post-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% if message %}
                        <div class="alert alert-success" role="alert">
                            Noticia Creada Correctamente
                        </div>
                    {% endif %}
                    {% for field in form %}
                    <div class="mb-3">
                        <label for="{{ field.name }}" class="form-label">{{ field.label }}</label>
                        {% render_field field class="form-control" %}
                      </div>
                      {% if field.errors %}
                      <ul>
                        {% for error in field.errors %}
                            <li style="color: #ff0000">{{ error }}</li>
                        {% endfor %}
                      </ul>
                      {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-2"></div>
</div>

<script>
    $('#id_categories').select2({
        placeholder: "Selecciona Categoría"
    });
</script>
{% endblock %}

blog_App/templates/edit_new.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
<div class="row">
    <div class="col-2"></div>
    <div class="col-8">
        <div class="card" style="width: 100%; background: #cbd5db;">
            <div class="card-header">
                <h3 class="card-title">Nueva Noticia</h3>
            </div>
            <div class="card-body">
                {% if form.errors %}
                   {{  form.errors }}
                {% endif %}
                <form method="POST" class="post-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="mb-3">
                        <label for="{{ field.name }}" class="form-label">{{ field.label }}</label>
                        {% render_field field class="form-control" %}
                      </div>
                      {% if field.errors %}
                      <ul>
                        {% for error in field.errors %}
                            <li style="color: #ff0000">{{ error }}</li>
                        {% endfor %}
                      </ul>
                      {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-2"></div>
</div>

<script>
    $('#id_categories').select2({
        placeholder: "Selecciona Categoría"
    });
</script>
{% endblock %}

blog_App/templates/home.html
{% extends "base.html" %} {% block title %}Inicio{% endblock %} {% block titleView %}Bienvenido{% endblock %} {% load static %} {% block content %}
<div class="bg-secondary bg-gradient rounded-1 ">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb p-2">
            <li class="breadcrumb-item active text-light" aria-current="page">Inicio</li>
        </ol>
    </nav>
</div>
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active ">
            <img src="https://cdn.pixabay.com/photo/2015/05/11/14/44/pencils-762555_1280.jpg " class="d-block w-100 " alt="... ">
        </div>
        <div class="carousel-item ">
            <img src="https://cdn.pixabay.com/photo/2017/01/18/08/25/social-media-1989152_1280.jpg " class="d-block w-100 " alt="... ">
        </div>
        <div class="carousel-item ">
            <img src="https://cdn.pixabay.com/photo/2018/07/15/10/45/system-3539317_1280.jpg" class="d-block w-100 " alt="... ">
        </div>
    </div>
    <button class="carousel-control-prev " type="button " data-bs-target="#carouselExampleIndicators " data-bs-slide="prev ">
      <span class="carousel-control-prev-icon " aria-hidden="true "></span>
      <span class="visually-hidden ">Previous</span>
    </button>
    <button class="carousel-control-next " type="button " data-bs-target="#carouselExampleIndicators " data-bs-slide="next ">
      <span class="carousel-control-next-icon " aria-hidden="true "></span>
      <span class="visually-hidden ">Next</span>
    </button>
</div>
<br> {% if user.is_authenticated %}
<div>
    <h1 class="text-center">¿Tienes nuevas Noticias?</h1>
    <h2 class="text-center">{{user.first_name}} {{user.last_name}}</h2>
</div>
{% else %}
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for new in news%}
    <div class="col">
        <div class="card h-100">
            <img class="img-card" src="{{new.image}}" class="card-img-top" alt="...">
            <div class="card-body">
                <div class="container-fluid">
                    <div class="row justify-content-between">
                        <div class="col-8">
                            <h5 class="card-title">{{new.title}}</h5>
                            <p class="card-text">{{new.author}}</p>
                        </div>
                        <div class="col-3 align-self-center">
                            <a href="{% url 'newsitem' new.id %}" class="card-link">Leer</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %} {% endblock %}

blog_App/templates/news_table.html
{% extends "base.html" %} {% block title %}Noticias{% endblock %} 
{% block titleView %}Administrar Noticias{% endblock %} 
{% load static %} {% block content %}
<div class="dropdown">
  <button
    class="btn btn-dark dropdown-toggle"
    data-bs-toggle="dropdown"
    aria-expanded="false"
  >
    Seleccione una Categoria
  </button>
  <ul class="dropdown-menu">
    {% for category in categories %}
    <li>
      <a href="{% url 'news_tableCategory' category.id %}"
        ><button type="button" class="btn" style="width: 150px">
          {{category.name}}
        </button></a
      >
    </li>
    {% endfor %}
    <li>
      <a href="{% url 'news_table' %}"
        ><button type="button" class="btn" style="width: 150px">
          Todos
        </button></a
      >
    </li>
  </ul>
</div>
<br />
<table class="table table-striped table-bordered" id="registers">
<thead>
    <tr>
    <th scope="col">Titulo</th>
    <th scope="col">Autor</th>
    <th scope="col"></th>
    <th scope="col"></th>
    <th scope="col"></th>
    </tr>
</thead>
<tbody>
    {% for new in news%}
    <tr>
    <td>{{new.title}}</td>
    <td>{{new.author}}</td>
    <td>
        <a
        href="{% url 'newsitem' new.id %}"
        class="btn btn-outline-success"
        >Leer</a
        >
    </td>
    <td>
        <a
        href="{% url 'update_new' new.id %}"
        class="btn btn-outline-primary"
        >Editar</a
        >
    </td>
    <td>
        <a
        href="{% url 'delete_new' new.id %}"
        class="btn btn-outline-danger"
        >Eliminar</a
        >
    </td>
    </tr>
    {% endfor %}
</tbody>
</table>
<script>
  $("#registers").DataTable({
    language: {
      emptyTable: "No hay información",
      info: "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
      infoEmpty: "Mostrando 0 to 0 of 0 Entradas",
      infoFiltered: "(Filtrado de _MAX_ total entradas)",
      lengthMenu: "Mostrar _MENU_ Entradas",
      loadingRecords: "Cargando...",
      processing: "Procesando...",
      search: "Buscar en Todos:",
      zeroRecords: "Sin resultados encontrados",
      paginate: {
        first: "Primero",
        last: "Ultimo",
        next: "Siguiente",
        previous: "Anterior",
      },
    },
      responsive: true,
      autoWidth: false
  });
</script>
{% endblock %}

blog_App/templates/newscategory.html
{% extends "base.html" %} {% block title %}Noticias {% endblock %} {% block titleView %}{{categories.name}} {% endblock %} {% load static %} {% block content %}
<div class="bg-secondary bg-gradient rounded-1 ">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb p-2">
            <li class="breadcrumb-item" aria-current="page"><a href="/home">Inicio</a></li>
            <li class="breadcrumb-item" aria-current="page"><a href="/news">News</a></li>
            <li class="breadcrumb-item active text-light" aria-current="page">{{categories.name}}</li>
        </ol>
    </nav>
</div>

<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for new in news%}
    <div class="col">
        <div class="card h-100">
            <img class="img-card" src="../../../../{{new.image}}" class="card-img-top" alt="...">
            <div class="card-body">
                <div class="container-fluid">
                    <div class="row justify-content-between">
                        <div class="col-8">
                            <h5 class="card-title">{{new.title}}</h5>
                            <p class="card-text">{{new.author}}</p>
                        </div>
                        <div class="col-3 align-self-center">
                            <a href="{% url 'newsitem' new.id %}" class="card-link">Leer</a>
                        </div>
                        {% if user.is_authenticated %}
                        <div class="col-3 align-self-center">
                            <a href="{% url 'update_new' new.id %}" class="card-link">Editar</a>
                        </div>
                        {% endif %}
                    </div>

                </div>

            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

blog_App/templates/newsindex.html
{% extends "base.html" %} {% block title %}Noticias{% endblock %} {% block titleView %}Noticias{% endblock %} {% load static %} {% block content %}
<div class="bg-secondary bg-gradient rounded-1 ">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb p-2">
            <li class="breadcrumb-item" aria-current="page"><a href="/home">Inicio</a></li>
            <li class="breadcrumb-item active text-light" aria-current="page">News</li>
        </ol>
    </nav>
</div>

<div class="dropdown">
    <button class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        Seleccione una Categoria
      </button>
    <ul class="dropdown-menu">
        {% for category in categories %}
        <li> <a href="{% url 'category' category.id %}"><button type="button" class="btn" style="width: 150px;">{{category.name}}</button></a></li>
        {% endfor %}
    </ul>
</div>
<br>
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for new in news%}
    <div class="col">
        <div class="card h-100">
            <img class="img-card" src="{{new.image}}" class="card-img-top" alt="...">
            <div class="card-body">
                <div class="container-fluid">
                    <div class="row justify-content-between">
                        <div class="col-8">
                            <h5 class="card-title">{{new.title}}</h5>
                            <p class="card-text">{{new.author}}</p>
                        </div>
                        <div class="col-3 align-self-center">
                            <a href="{% url 'newsitem' new.id %}" class="card-link">Leer</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}